version: '2'
services:
  mock_server:
    image: mockserver/mockserver:mockserver-5.10.0
  mock_tester:
    build:
      context: .
      dockerfile: resources/docker/tester/Dockerfile
    volumes:
      - ./src:/home/robot/src
      - ./tests/robot/tests:/home/robot/tests
      - ./tests/robot/logs:/home/robot/logs
    environment:
      - MOCK_URL=http://mock_server:1080
      - ROBOT_ARGS
    depends_on:
      - mock_server
